config/routes.rb
Rails.application.routes.draw do
 resources :books
 root :to => redirect('/books')
 get '/books/:id/similar_books' => 'books#search_similar_books',
 as: :search_similar_books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ActiveRecord::Base
    # add to app/models/Book.rb
    def self.all_genres ; %w[Fiction Drama Adventure Romance Mystery Horror] ; end # shortcut: array of strings
    
    validates :title, :presence => true
    validates :publish_date, :presence => true
    validate :publish_1930_or_later # uses custom validator below
    validates :genre, :inclusion => {:in => Book.all_genres},
      :unless => :grandfathered?
 
    def publish_1930_or_later
      errors.add(:publish_date, 'must be 1930 or later') if
        publish_date && publish_date < Date.parse('1 Jan 1930')
    end
 
    @@grandfathered_date = Date.parse('1 Nov 1968')
 
    def grandfathered?
      publish_date && publish_date < @@grandfathered_date
    end
    
    
    def self.similar_books(book)
      Book.where author: book.author
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 
  def index
    sort = params[:sort] || session[:sort]
    case sort
    when 'title'
     ordering,@title_header = {:title => :asc}, 'hilite'
    when 'publish_date'
     ordering,@date_header = {:publish_date => :asc}, 'hilite'
    when 'genre'
     ordering,@genre_header = {:genre => :asc}, 'hilite'
    end
    
    @all_genres = Book.all_genres
    @selected_genres = params[:genres] || session[:genres] || {}
     
    if @selected_genres == {}
      @selected_genres = Hash[@all_genres.map {|genre| [genre, genre]}]
    end
     
    if params[:sort] != session[:sort] or params[:genres] != session[:genres]
      session[:sort] = sort
      session[:genres] = @selected_genres
      redirect_to :sort => sort, :genres => @selected_genres and return
    end
    @books = Book.where(genre: @selected_genres.keys).order(ordering)
  end
 
 def show
  id = params[:id] # retrieve book ID from URI route
  @book = Book.find(id) # look up book by unique ID
  # will render app/views/books/show.html.haml by default
 end
 
 def new
  @book = Book.new
  # default: render 'new' template
 end
 
 def create
  params.require(:book)
  permitted = params[:book].permit(:title,:genre,:publish_date, :isbn_number, :description, :author)
  @book = Book.new(permitted)
    if @book.save
      flash[:notice] = "#{@book.title} was successfully created."
      redirect_to books_path
    else
      render 'new' # note, 'new' template can access @book's field values!
    end
 end
 
 def edit
  @book = Book.find params[:id]
 end
 
 def update
  @book = Book.find params[:id]
  params.require(:book)
  permitted = params[:book].permit(:title,:genre,:publish_date, :isbn_number, :description, :author)
  @book.update_attributes!(permitted)
  flash[:notice] = "#{@book.title} was successfully updated."
  redirect_to book_path(@book)
 end
 
 def destroy
  @book = Book.find(params[:id])
  @book.destroy
  flash[:notice] = "Book '#{@book.title}' was deleted."
  redirect_to books_path
 end
 
 def search_similar_books
  @book = Book.find(params[:id])
  if @book.author.nil? || @book.author.empty?
    flash[:warning]= "'#{@book.title}' has no author info"
    redirect_to books_path
  else
   @books = Book.similar_books(@book)
  end
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.haml
%h2 Edit Book
 
= form_tag book_path(@book), :method => :put do
 
  = label :book, :title, 'Title'
  = text_field :book, :title
 
  = label :book, :genre, 'Genre'
  = select :book, :genre, ['Fiction','Drama','Adventure','Romance','Mystery', 'Horror']
 
  = label :book, :publish_date, 'Published On'
  = date_select :book, :publish_date
  
  = label :book, :description, 'Description'
  = text_field :book, :description
  
  = label :book, :author, 'Author'
  = text_field :book, 'author'
 
  = submit_tag 'Update Book Info'

app/views/books/index.html.haml
-#  This file is app/views/books/index.html.haml
%h1 All Books

 
= form_tag books_path, :method => :get, :id => 'genre_form' do
  = hidden_field_tag "title_sort", true if @title_header
  = hidden_field_tag ":publish_date_sort", true if @date_header
  Include:
  - @all_genres.each do |genre|
    = genre
    = check_box_tag "genres[#{genre}]", 1, @selected_genres.include?(genre), :id => "genres_#{genre}"
  = submit_tag 'Refresh', :id => 'genres_submit'

%table#books
  %thead
    %tr
      %th{:class => @title_header}= link_to 'Book Title', books_path(:sort => 'title'), :id => 'title_header'
      %th{:class => @genre_header}= link_to 'Genre', books_path(:sort => 'genre'), :id => 'genre_header'
      %th{:class => @date_header}= link_to 'Publish Date', books_path(:sort => 'publish_date'), :id => 'publish_date_header'
      %th More Info
  %tbody
    - @books.each do |book|
      %tr
        %td= book.title 
        %td= book.genre
        %td= book.publish_date.strftime("%B %d, %Y")
        %td= link_to "More about #{book.title}", book_path(book)
-# add to end of index.html.haml
= link_to 'Add new book', new_book_path

app/views/books/new.html.haml
%h2 Create New Book
 
= form_tag books_path, :method => :post do
 
  = label :book, :title, 'Title'
  = text_field :book, :title
 
  = label :book, :genre, 'Genre'
  = select :book, :genre, ['Fiction','Drama','Adventure','Romance','Mystery', 'Horror']
 
  = label :book, :publish_date, 'Published On'
  = date_select :book, :publish_date
  
  = label :book, :isbn_number, 'ISBN Number'
  = text_field :book, :isbn_number
  
  = label :book, :description, 'Description'
  = text_field :book, :description
  
  = label :book, :author, 'Author'
  = text_field :book, :author
 
  = submit_tag 'Save Changes'

app/views/books/search_similar_books.html.haml
%h1 Similar books to #{@book.title}

%table#similar_books
  %thead
    %tr
      %th Book Title
      %th Genre
      %th Publish Date
      %th Author
      %th More Info
  %tbody
    - @books.each do |book|
      %tr
        %td= book.title 
        %td= book.genre
        %td= book.publish_date.strftime("%B %d, %Y")
        %td= book.author
        %td= link_to "More about #{book.title}", book_path(book)

app/views/books/show.html.haml
-# in app/views/movies/show.html.haml
%h2 Details about #{@book.title}
 
%ul#details
  %li
    Genre:
    = @book.genre
  %li
    Published on:
    = @book.publish_date.strftime("%B %d, %Y")
  %li
    ISBN number:
    =@book.isbn_number
  %li
    Description:
    = @book.description
    
%h3 Author:
 
%p#author= @book.author
 
= link_to 'Edit info', edit_book_path(@book)
= link_to 'Find Books With Same Author', search_similar_books_url(id: @book.id)
= link_to 'Delete', book_path(@book), :method => :delete
= link_to 'Back to books list', books_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title My Books!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
 
  %body
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
    #main
      = yield